
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Battle
{
public sealed partial class AttackConfig : Luban.BeanBase
{
    public AttackConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LegacyId = _buf.ReadString();
        NameCn = _buf.ReadString();
        Desc = _buf.ReadString();
        Animation = _buf.ReadString();
        PowerScale = GameLogic.Config.ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        FlatPower = _buf.ReadInt();
        DamageKind = (Battle.DamageKind)_buf.ReadInt();
        Knockback = GameLogic.Config.ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        WsGain = GameLogic.Config.ExternalTypeUtil.NewVector2I(global::GameConfig.vector2i.Deserializevector2i(_buf));
        HitProtect = _buf.ReadInt();
        Interval = _buf.ReadFloat();
    }

    public static AttackConfig DeserializeAttackConfig(ByteBuf _buf)
    {
        return new Battle.AttackConfig(_buf);
    }

    /// <summary>
    /// 攻击ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 旧 objattackDic 键名
    /// </summary>
    public readonly string LegacyId;
    /// <summary>
    /// 中文名
    /// </summary>
    public readonly string NameCn;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 播放的动画名
    /// </summary>
    public readonly string Animation;
    /// <summary>
    /// 攻击力倍率范围(乘英雄攻击,X=下限,Y=上限)
    /// </summary>
    public readonly Godot.Vector2 PowerScale;
    /// <summary>
    /// 固定攻击力(不与属性挂钩)
    /// </summary>
    public readonly int FlatPower;
    /// <summary>
    /// 伤害类型
    /// </summary>
    public readonly Battle.DamageKind DamageKind;
    /// <summary>
    /// 击退(旧 hurtBack[0]/[1],X=横向,Y=纵向)
    /// </summary>
    public readonly Godot.Vector2 Knockback;
    /// <summary>
    /// 命中获得无双值范围(旧 WSValue,X=下限,Y=上限)
    /// </summary>
    public readonly Godot.Vector2I WsGain;
    /// <summary>
    /// 受击保护累计值(旧 HitProtect)
    /// </summary>
    public readonly int HitProtect;
    /// <summary>
    /// 本段最短停留秒(动画不足时补足,即普攻之间的间隔)
    /// </summary>
    public readonly float Interval;
   
    public const int __ID__ = 818309408;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "LegacyId:" + LegacyId + ","
        + "NameCn:" + NameCn + ","
        + "Desc:" + Desc + ","
        + "Animation:" + Animation + ","
        + "PowerScale:" + PowerScale + ","
        + "FlatPower:" + FlatPower + ","
        + "DamageKind:" + DamageKind + ","
        + "Knockback:" + Knockback + ","
        + "WsGain:" + WsGain + ","
        + "HitProtect:" + HitProtect + ","
        + "Interval:" + Interval + ","
        + "}";
    }
}
}

