
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Battle
{
public sealed partial class AttackConfig : Luban.BeanBase
{
    public AttackConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LegacyId = _buf.ReadString();
        NameCn = _buf.ReadString();
        Desc = _buf.ReadString();
        Animation = _buf.ReadString();
        PowerScale = GameLogic.Config.ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        FlatPower = _buf.ReadInt();
        DamageKind = (Battle.DamageKind)_buf.ReadInt();
        Knockback = GameLogic.Config.ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        WsGain = GameLogic.Config.ExternalTypeUtil.NewVector2I(global::GameConfig.vector2i.Deserializevector2i(_buf));
        HitProtect = _buf.ReadInt();
        SoundId = (Sound.SoundId)_buf.ReadInt();
        HitSoundId = (Sound.SoundId)_buf.ReadInt();
        OwnerId = (Entity.EntityId)_buf.ReadInt();
        ComboIndex = _buf.ReadInt();
        AiWeight = _buf.ReadInt();
        AiPriority = _buf.ReadInt();
        AiRange = GameLogic.Config.ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        AiCooldown = GameLogic.Config.ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        AiInitCooldown = GameLogic.Config.ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
    }

    public static AttackConfig DeserializeAttackConfig(ByteBuf _buf)
    {
        return new Battle.AttackConfig(_buf);
    }

    /// <summary>
    /// 攻击ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 旧 objattackDic 键名
    /// </summary>
    public readonly string LegacyId;
    /// <summary>
    /// 中文名
    /// </summary>
    public readonly string NameCn;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 播放的动画名
    /// </summary>
    public readonly string Animation;
    /// <summary>
    /// 攻击力倍率范围(乘英雄攻击,X=下限,Y=上限,写法 1,1.2)
    /// </summary>
    public readonly Godot.Vector2 PowerScale;
    /// <summary>
    /// 固定攻击力(不与属性挂钩)
    /// </summary>
    public readonly int FlatPower;
    /// <summary>
    /// 伤害类型
    /// </summary>
    public readonly Battle.DamageKind DamageKind;
    /// <summary>
    /// 击退(X&gt;0=远离攻击者,Y&lt;0=向上;单位同旧 hurtBack,乘 BattleConfig.KnockbackScale* 换算 px/s,写法 2,0)
    /// </summary>
    public readonly Godot.Vector2 Knockback;
    /// <summary>
    /// 命中获得无双值范围(旧 WSValue,X=下限,Y=上限,写法 3,5)
    /// </summary>
    public readonly Godot.Vector2I WsGain;
    /// <summary>
    /// 受击保护累计值(旧 HitProtect)
    /// </summary>
    public readonly int HitProtect;
    /// <summary>
    /// 起手音效(SoundConfig;None=无)
    /// </summary>
    public readonly Sound.SoundId SoundId;
    /// <summary>
    /// 命中音效(打中目标时播,None=无;旧项目按攻击者选音)
    /// </summary>
    public readonly Sound.SoundId HitSoundId;
    /// <summary>
    /// 这招属于谁(None=通用招,将来多主体共享用)
    /// </summary>
    public readonly Entity.EntityId OwnerId;
    /// <summary>
    /// 连段第几段(0起;同一 OwnerId 内连续,越大越靠后)
    /// </summary>
    public readonly int ComboIndex;
    /// <summary>
    /// AI 选招权重(怪物 AI 用;英雄普攻填 0)
    /// </summary>
    public readonly int AiWeight;
    /// <summary>
    /// AI 优先级:0=普攻池(按攻击欲望掷骰+权重抽);&gt;0=技能(冷却就绪且距离满足即放,大者优先,追击途中也会放)
    /// </summary>
    public readonly int AiPriority;
    /// <summary>
    /// AI 释放距离 px(X=最小,Y=最大;只比水平距离,写法 0,45)
    /// </summary>
    public readonly Godot.Vector2 AiRange;
    /// <summary>
    /// AI 释放后冷却秒(X=下限,Y=上限随机;普攻池填 0,0)
    /// </summary>
    public readonly Godot.Vector2 AiCooldown;
    /// <summary>
    /// AI 出生时初始冷却秒(X=下限,Y=上限;旧 _ready 里 Skill_N_CD=randi_range)
    /// </summary>
    public readonly Godot.Vector2 AiInitCooldown;
   
    public const int __ID__ = 818309408;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "LegacyId:" + LegacyId + ","
        + "NameCn:" + NameCn + ","
        + "Desc:" + Desc + ","
        + "Animation:" + Animation + ","
        + "PowerScale:" + PowerScale + ","
        + "FlatPower:" + FlatPower + ","
        + "DamageKind:" + DamageKind + ","
        + "Knockback:" + Knockback + ","
        + "WsGain:" + WsGain + ","
        + "HitProtect:" + HitProtect + ","
        + "SoundId:" + SoundId + ","
        + "HitSoundId:" + HitSoundId + ","
        + "OwnerId:" + OwnerId + ","
        + "ComboIndex:" + ComboIndex + ","
        + "AiWeight:" + AiWeight + ","
        + "AiPriority:" + AiPriority + ","
        + "AiRange:" + AiRange + ","
        + "AiCooldown:" + AiCooldown + ","
        + "AiInitCooldown:" + AiInitCooldown + ","
        + "}";
    }
}
}

