
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Battle
{
public sealed partial class AttackConfig : Luban.BeanBase
{
    public AttackConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LegacyId = _buf.ReadString();
        NameCn = _buf.ReadString();
        Desc = _buf.ReadString();
        Animation = _buf.ReadString();
        PowerScaleMin = _buf.ReadFloat();
        PowerScaleMax = _buf.ReadFloat();
        FlatPower = _buf.ReadInt();
        DamageKind = (Battle.DamageKind)_buf.ReadInt();
        KnockbackX = _buf.ReadFloat();
        KnockbackY = _buf.ReadFloat();
        WsGainMin = _buf.ReadInt();
        WsGainMax = _buf.ReadInt();
        HitProtect = _buf.ReadInt();
        HitInterval = _buf.ReadFloat();
    }

    public static AttackConfig DeserializeAttackConfig(ByteBuf _buf)
    {
        return new Battle.AttackConfig(_buf);
    }

    /// <summary>
    /// 攻击ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 旧 objattackDic 键名
    /// </summary>
    public readonly string LegacyId;
    /// <summary>
    /// 中文名
    /// </summary>
    public readonly string NameCn;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 播放的动画名
    /// </summary>
    public readonly string Animation;
    /// <summary>
    /// 攻击力倍率下限(乘英雄攻击)
    /// </summary>
    public readonly float PowerScaleMin;
    /// <summary>
    /// 攻击力倍率上限(乘英雄攻击)
    /// </summary>
    public readonly float PowerScaleMax;
    /// <summary>
    /// 固定攻击力(不与属性挂钩)
    /// </summary>
    public readonly int FlatPower;
    /// <summary>
    /// 伤害类型
    /// </summary>
    public readonly Battle.DamageKind DamageKind;
    /// <summary>
    /// 击退横向分量(旧 hurtBack[0])
    /// </summary>
    public readonly float KnockbackX;
    /// <summary>
    /// 击退纵向分量(旧 hurtBack[1])
    /// </summary>
    public readonly float KnockbackY;
    /// <summary>
    /// 命中获得无双值下限(旧 WSValue)
    /// </summary>
    public readonly int WsGainMin;
    /// <summary>
    /// 命中获得无双值上限(旧 WSValue)
    /// </summary>
    public readonly int WsGainMax;
    /// <summary>
    /// 受击保护累计值(旧 HitProtect)
    /// </summary>
    public readonly int HitProtect;
    /// <summary>
    /// 同招连击间隔秒(旧 HitInterv)
    /// </summary>
    public readonly float HitInterval;
   
    public const int __ID__ = 818309408;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "LegacyId:" + LegacyId + ","
        + "NameCn:" + NameCn + ","
        + "Desc:" + Desc + ","
        + "Animation:" + Animation + ","
        + "PowerScaleMin:" + PowerScaleMin + ","
        + "PowerScaleMax:" + PowerScaleMax + ","
        + "FlatPower:" + FlatPower + ","
        + "DamageKind:" + DamageKind + ","
        + "KnockbackX:" + KnockbackX + ","
        + "KnockbackY:" + KnockbackY + ","
        + "WsGainMin:" + WsGainMin + ","
        + "WsGainMax:" + WsGainMax + ","
        + "HitProtect:" + HitProtect + ","
        + "HitInterval:" + HitInterval + ","
        + "}";
    }
}
}

