
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Battle
{
public sealed partial class BattleConfig : Luban.BeanBase
{
    public BattleConfig(ByteBuf _buf) 
    {
        NameCn = _buf.ReadString();
        Desc = _buf.ReadString();
        DefKHero = _buf.ReadFloat();
        MdefKHero = _buf.ReadFloat();
        MissKHero = _buf.ReadFloat();
        DefKMonster = _buf.ReadFloat();
        MdefKMonster = _buf.ReadFloat();
        MissKMonster = _buf.ReadFloat();
        CritK = _buf.ReadFloat();
        LuckyKHeroAtk = _buf.ReadFloat();
        LuckyKMonsterAtk = _buf.ReadFloat();
        CritBase = _buf.ReadFloat();
        LvMissCoefHeroDef = _buf.ReadFloat();
        LvCritCoefHeroDef = _buf.ReadFloat();
        LvMissCoefMonsterDef = _buf.ReadFloat();
        LvCritCoefMonsterDef = _buf.ReadFloat();
        LvLuckyCoef = _buf.ReadFloat();
        LvDamageCoef = _buf.ReadFloat();
    }

    public static BattleConfig DeserializeBattleConfig(ByteBuf _buf)
    {
        return new Battle.BattleConfig(_buf);
    }

    /// <summary>
    /// 中文名
    /// </summary>
    public readonly string NameCn;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 英雄作防守方时物防减伤K: x/(x+K)
    /// </summary>
    public readonly float DefKHero;
    /// <summary>
    /// 英雄作防守方时魔防减伤K
    /// </summary>
    public readonly float MdefKHero;
    /// <summary>
    /// 英雄作防守方时被命中K: Miss/(Miss+K)
    /// </summary>
    public readonly float MissKHero;
    /// <summary>
    /// 怪物作防守方时物防减伤K
    /// </summary>
    public readonly float DefKMonster;
    /// <summary>
    /// 怪物作防守方时魔防减伤K
    /// </summary>
    public readonly float MdefKMonster;
    /// <summary>
    /// 怪物作防守方时被命中K
    /// </summary>
    public readonly float MissKMonster;
    /// <summary>
    /// 暴击率基数: Crit/(Crit+K)
    /// </summary>
    public readonly float CritK;
    /// <summary>
    /// 英雄攻击时暴击倍率幸运K
    /// </summary>
    public readonly float LuckyKHeroAtk;
    /// <summary>
    /// 怪物攻击时暴击倍率幸运K
    /// </summary>
    public readonly float LuckyKMonsterAtk;
    /// <summary>
    /// 暴击倍率基数: CritBase + Lucky/(Lucky+K)
    /// </summary>
    public readonly float CritBase;
    /// <summary>
    /// 等级压制-英雄防守闪避系数
    /// </summary>
    public readonly float LvMissCoefHeroDef;
    /// <summary>
    /// 等级压制-英雄防守暴击系数
    /// </summary>
    public readonly float LvCritCoefHeroDef;
    /// <summary>
    /// 等级压制-怪物防守闪避系数
    /// </summary>
    public readonly float LvMissCoefMonsterDef;
    /// <summary>
    /// 等级压制-怪物防守暴击系数
    /// </summary>
    public readonly float LvCritCoefMonsterDef;
    /// <summary>
    /// 等级压制-幸运系数
    /// </summary>
    public readonly float LvLuckyCoef;
    /// <summary>
    /// 等级压制-每级伤害系数
    /// </summary>
    public readonly float LvDamageCoef;
   
    public const int __ID__ = -1776797808;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "NameCn:" + NameCn + ","
        + "Desc:" + Desc + ","
        + "DefKHero:" + DefKHero + ","
        + "MdefKHero:" + MdefKHero + ","
        + "MissKHero:" + MissKHero + ","
        + "DefKMonster:" + DefKMonster + ","
        + "MdefKMonster:" + MdefKMonster + ","
        + "MissKMonster:" + MissKMonster + ","
        + "CritK:" + CritK + ","
        + "LuckyKHeroAtk:" + LuckyKHeroAtk + ","
        + "LuckyKMonsterAtk:" + LuckyKMonsterAtk + ","
        + "CritBase:" + CritBase + ","
        + "LvMissCoefHeroDef:" + LvMissCoefHeroDef + ","
        + "LvCritCoefHeroDef:" + LvCritCoefHeroDef + ","
        + "LvMissCoefMonsterDef:" + LvMissCoefMonsterDef + ","
        + "LvCritCoefMonsterDef:" + LvCritCoefMonsterDef + ","
        + "LvLuckyCoef:" + LvLuckyCoef + ","
        + "LvDamageCoef:" + LvDamageCoef + ","
        + "}";
    }
}
}

