
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Battle
{ 
    public enum DamageKind
    {
        /// <summary>
        /// 物理
        /// </summary>
        Physics = 0,
        /// <summary>
        /// 魔法
        /// </summary>
        Magic = 1,
        /// <summary>
        /// 真实
        /// </summary>
        Real = 2,
    }

} 

