
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Battle
{
public partial class TbAttackConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Battle.AttackConfig> _dataMap;
    private readonly System.Collections.Generic.List<Battle.AttackConfig> _dataList;
    
    public TbAttackConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Battle.AttackConfig>(n);
        _dataList = new System.Collections.Generic.List<Battle.AttackConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Battle.AttackConfig _v;
            _v = global::GameConfig.Battle.AttackConfig.DeserializeAttackConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Battle.AttackConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Battle.AttackConfig> DataList => _dataList;

    public Battle.AttackConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Battle.AttackConfig Get(int key) => _dataMap[key];
    public Battle.AttackConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

