
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Battle
{
public partial class TbBattleConfig
{

     private readonly Battle.BattleConfig _data;

     public Battle.BattleConfig Data => _data;

    public TbBattleConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::GameConfig.Battle.BattleConfig.DeserializeBattleConfig(_buf);
    }


    /// <summary>
    /// 中文名
    /// </summary>
     public string NameCn => _data.NameCn;
    /// <summary>
    /// 描述
    /// </summary>
     public string Desc => _data.Desc;
    /// <summary>
    /// 英雄作防守方时物防减伤K: x/(x+K)
    /// </summary>
     public float DefKHero => _data.DefKHero;
    /// <summary>
    /// 英雄作防守方时魔防减伤K
    /// </summary>
     public float MdefKHero => _data.MdefKHero;
    /// <summary>
    /// 英雄作防守方时被命中K: Miss/(Miss+K)
    /// </summary>
     public float MissKHero => _data.MissKHero;
    /// <summary>
    /// 怪物作防守方时物防减伤K
    /// </summary>
     public float DefKMonster => _data.DefKMonster;
    /// <summary>
    /// 怪物作防守方时魔防减伤K
    /// </summary>
     public float MdefKMonster => _data.MdefKMonster;
    /// <summary>
    /// 怪物作防守方时被命中K
    /// </summary>
     public float MissKMonster => _data.MissKMonster;
    /// <summary>
    /// 暴击率基数: Crit/(Crit+K)
    /// </summary>
     public float CritK => _data.CritK;
    /// <summary>
    /// 英雄攻击时暴击倍率幸运K
    /// </summary>
     public float LuckyKHeroAtk => _data.LuckyKHeroAtk;
    /// <summary>
    /// 怪物攻击时暴击倍率幸运K
    /// </summary>
     public float LuckyKMonsterAtk => _data.LuckyKMonsterAtk;
    /// <summary>
    /// 暴击倍率基数: CritBase + Lucky/(Lucky+K)
    /// </summary>
     public float CritBase => _data.CritBase;
    /// <summary>
    /// 等级压制-英雄防守闪避系数
    /// </summary>
     public float LvMissCoefHeroDef => _data.LvMissCoefHeroDef;
    /// <summary>
    /// 等级压制-英雄防守暴击系数
    /// </summary>
     public float LvCritCoefHeroDef => _data.LvCritCoefHeroDef;
    /// <summary>
    /// 等级压制-怪物防守闪避系数
    /// </summary>
     public float LvMissCoefMonsterDef => _data.LvMissCoefMonsterDef;
    /// <summary>
    /// 等级压制-怪物防守暴击系数
    /// </summary>
     public float LvCritCoefMonsterDef => _data.LvCritCoefMonsterDef;
    /// <summary>
    /// 等级压制-幸运系数
    /// </summary>
     public float LvLuckyCoef => _data.LvLuckyCoef;
    /// <summary>
    /// 等级压制-每级伤害系数
    /// </summary>
     public float LvDamageCoef => _data.LvDamageCoef;
    /// <summary>
    /// 等级压制-英雄防守闪避系数封顶
    /// </summary>
     public float LvMissCapHeroDef => _data.LvMissCapHeroDef;
    /// <summary>
    /// 等级压制-怪物防守闪避系数封顶
    /// </summary>
     public float LvMissCapMonsterDef => _data.LvMissCapMonsterDef;
    /// <summary>
    /// 等级压制-暴击系数封顶(人怪两侧一致)
    /// </summary>
     public float LvCritCap => _data.LvCritCap;
    /// <summary>
    /// 等级压制-幸运系数封顶(人怪两侧一致)
    /// </summary>
     public float LvLuckyCap => _data.LvLuckyCap;
    /// <summary>
    /// 等级压制-英雄防守时伤害最多按几级算
    /// </summary>
     public int LvDamageCapLvHeroDef => _data.LvDamageCapLvHeroDef;
    /// <summary>
    /// 等级压制-怪物防守时伤害最多按几级算
    /// </summary>
     public int LvDamageCapLvMonsterDef => _data.LvDamageCapLvMonsterDef;
    /// <summary>
    /// 英雄被击退横向换算: px/s = Knockback.X &#215; 本值
    /// </summary>
     public float KnockbackScaleXHeroDef => _data.KnockbackScaleXHeroDef;
    /// <summary>
    /// 怪物被击退横向换算: px/s = Knockback.X &#215; 本值
    /// </summary>
     public float KnockbackScaleXMonsterDef => _data.KnockbackScaleXMonsterDef;
    /// <summary>
    /// 击退纵向换算: px/s = Knockback.Y &#215; 本值(人怪一致)
    /// </summary>
     public float KnockbackScaleY => _data.KnockbackScaleY;
    /// <summary>
    /// 无双值上限(旧项目 BaseRoleProperies.gd:20)
    /// </summary>
     public int WsMax => _data.WsMax;
    /// <summary>
    /// 英雄死亡后自动重开本关的等待秒数(含死亡动画 1.1 秒)
    /// </summary>
     public float DeathRestartDelay => _data.DeathRestartDelay;
    /// <summary>
    /// 通关后自动重开本关的等待秒数(暂无结算界面时使用)
    /// </summary>
     public float ClearRestartDelay => _data.ClearRestartDelay;
    /// <summary>
    /// 无双持续秒数（旧项目每0.5秒扣4/100，共12.5秒）
    /// </summary>
     public float WsDuration => _data.WsDuration;
    /// <summary>
    /// 无双攻击力独立倍率（旧项目1.5）
    /// </summary>
     public float WsPowerMultiplier => _data.WsPowerMultiplier;
    /// <summary>
    /// 无双横向移速倍率（旧项目1.5）
    /// </summary>
     public float WsMoveSpeedMultiplier => _data.WsMoveSpeedMultiplier;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

