
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Stat
{ 
    public enum StatModifierKind
    {
        /// <summary>
        /// 固定值
        /// </summary>
        Flat = 0,
        /// <summary>
        /// 同类百分比相加
        /// </summary>
        PercentAdd = 1,
        /// <summary>
        /// 独立百分比相乘
        /// </summary>
        PercentMult = 2,
    }

} 

