
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Stat
{ 
    public enum StatType
    {
        /// <summary>
        /// 生命上限
        /// </summary>
        MaxHp = 0,
        /// <summary>
        /// 魔法上限
        /// </summary>
        MaxMp = 1,
        /// <summary>
        /// 攻击
        /// </summary>
        Power = 2,
        /// <summary>
        /// 物防
        /// </summary>
        Def = 3,
        /// <summary>
        /// 魔防
        /// </summary>
        Mdef = 4,
        /// <summary>
        /// 暴击
        /// </summary>
        Crit = 5,
        /// <summary>
        /// 闪避
        /// </summary>
        Miss = 6,
        /// <summary>
        /// 幸运(加暴击倍率)
        /// </summary>
        Lucky = 7,
        /// <summary>
        /// 韧性(减对方幸运)
        /// </summary>
        Toughness = 8,
        /// <summary>
        /// 命中(减对方闪避)
        /// </summary>
        Htarget = 9,
        /// <summary>
        /// 暴击抵抗
        /// </summary>
        CritReduce = 10,
        /// <summary>
        /// 破甲(减对方物防)
        /// </summary>
        Ar = 11,
        /// <summary>
        /// 破魔(减对方魔防)
        /// </summary>
        Sp = 12,
        /// <summary>
        /// 吸血(百分点,伤害转生命)
        /// </summary>
        Vampirism = 13,
        /// <summary>
        /// 每秒回血
        /// </summary>
        HpRegen = 14,
        /// <summary>
        /// 每秒回蓝
        /// </summary>
        MpRegen = 15,
    }

} 

