
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Stat
{
/// <summary>
/// 一组完整属性值；英雄逐级成长行与怪物配置共用
/// </summary>
public sealed partial class StatBlock : Luban.BeanBase
{
    public StatBlock(ByteBuf _buf) 
    {
        MaxHp = _buf.ReadInt();
        MaxMp = _buf.ReadInt();
        Power = _buf.ReadInt();
        Def = _buf.ReadInt();
        Mdef = _buf.ReadInt();
        Crit = _buf.ReadInt();
        Miss = _buf.ReadInt();
        Lucky = _buf.ReadInt();
        Toughness = _buf.ReadInt();
        Htarget = _buf.ReadInt();
        CritReduce = _buf.ReadInt();
        Ar = _buf.ReadInt();
        Sp = _buf.ReadInt();
        Vampirism = _buf.ReadInt();
        HpRegen = _buf.ReadInt();
        MpRegen = _buf.ReadInt();
    }

    public static StatBlock DeserializeStatBlock(ByteBuf _buf)
    {
        return new Stat.StatBlock(_buf);
    }

    /// <summary>
    /// 生命上限
    /// </summary>
    public readonly int MaxHp;
    /// <summary>
    /// 魔法上限
    /// </summary>
    public readonly int MaxMp;
    /// <summary>
    /// 攻击
    /// </summary>
    public readonly int Power;
    /// <summary>
    /// 物防
    /// </summary>
    public readonly int Def;
    /// <summary>
    /// 魔防
    /// </summary>
    public readonly int Mdef;
    /// <summary>
    /// 暴击
    /// </summary>
    public readonly int Crit;
    /// <summary>
    /// 闪避
    /// </summary>
    public readonly int Miss;
    /// <summary>
    /// 幸运(加暴击倍率)
    /// </summary>
    public readonly int Lucky;
    /// <summary>
    /// 韧性(减对方幸运)
    /// </summary>
    public readonly int Toughness;
    /// <summary>
    /// 命中(减对方闪避)
    /// </summary>
    public readonly int Htarget;
    /// <summary>
    /// 暴击抵抗
    /// </summary>
    public readonly int CritReduce;
    /// <summary>
    /// 破甲(减对方物防)
    /// </summary>
    public readonly int Ar;
    /// <summary>
    /// 破魔(减对方魔防)
    /// </summary>
    public readonly int Sp;
    /// <summary>
    /// 吸血(百分点,伤害转生命)
    /// </summary>
    public readonly int Vampirism;
    /// <summary>
    /// 每秒回血
    /// </summary>
    public readonly int HpRegen;
    /// <summary>
    /// 每秒回蓝
    /// </summary>
    public readonly int MpRegen;
   
    public const int __ID__ = -1901719681;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "MaxHp:" + MaxHp + ","
        + "MaxMp:" + MaxMp + ","
        + "Power:" + Power + ","
        + "Def:" + Def + ","
        + "Mdef:" + Mdef + ","
        + "Crit:" + Crit + ","
        + "Miss:" + Miss + ","
        + "Lucky:" + Lucky + ","
        + "Toughness:" + Toughness + ","
        + "Htarget:" + Htarget + ","
        + "CritReduce:" + CritReduce + ","
        + "Ar:" + Ar + ","
        + "Sp:" + Sp + ","
        + "Vampirism:" + Vampirism + ","
        + "HpRegen:" + HpRegen + ","
        + "MpRegen:" + MpRegen + ","
        + "}";
    }
}
}

