
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Entity
{ 
    public enum EntityId
    {
        /// <summary>
        /// 悟空
        /// </summary>
        Wukong = 0,
        /// <summary>
        /// 花果山猴子
        /// </summary>
        HuaguoshanMonkey = 1,
        /// <summary>
        /// 妖猴
        /// </summary>
        DemonMonkey = 2,
    }

} 

