
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Profile
{
public sealed partial class ProfileConfig : Luban.BeanBase
{
    public ProfileConfig(ByteBuf _buf) 
    {
        NameCn = _buf.ReadString();
        Desc = _buf.ReadString();
        StartHeroId = _buf.ReadInt();
        StartGold = _buf.ReadInt();
    }

    public static ProfileConfig DeserializeProfileConfig(ByteBuf _buf)
    {
        return new Profile.ProfileConfig(_buf);
    }

    /// <summary>
    /// 中文名
    /// </summary>
    public readonly string NameCn;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 新档的出战英雄(HeroConfig.Id)
    /// </summary>
    public readonly int StartHeroId;
    /// <summary>
    /// 新档初始金币
    /// </summary>
    public readonly int StartGold;
   
    public const int __ID__ = -1299972474;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "NameCn:" + NameCn + ","
        + "Desc:" + Desc + ","
        + "StartHeroId:" + StartHeroId + ","
        + "StartGold:" + StartGold + ","
        + "}";
    }
}
}

