
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Profile
{
public partial class TbProfileConfig
{

     private readonly Profile.ProfileConfig _data;

     public Profile.ProfileConfig Data => _data;

    public TbProfileConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::GameConfig.Profile.ProfileConfig.DeserializeProfileConfig(_buf);
    }


    /// <summary>
    /// 中文名
    /// </summary>
     public string NameCn => _data.NameCn;
    /// <summary>
    /// 描述
    /// </summary>
     public string Desc => _data.Desc;
    /// <summary>
    /// 新档的出战英雄(HeroConfig.Id)
    /// </summary>
     public int StartHeroId => _data.StartHeroId;
    /// <summary>
    /// 新档初始金币
    /// </summary>
     public int StartGold => _data.StartGold;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

