
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Sound
{ 
    public enum SoundId
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 悟空挥棍2
        /// </summary>
        WukongAttack2 = 1,
        /// <summary>
        /// 悟空挥棍1/3
        /// </summary>
        WukongAttack1And3 = 2,
        /// <summary>
        /// 悟空挥棍4
        /// </summary>
        WukongAttack4 = 3,
        /// <summary>
        /// 悟空受击语音
        /// </summary>
        WukongHurt = 4,
        /// <summary>
        /// 悟空死亡语音
        /// </summary>
        WukongDeath = 5,
        /// <summary>
        /// 悟空命中音(棍打中东西)
        /// </summary>
        WukongImpact = 6,
        /// <summary>
        /// 花果山关卡背景音乐
        /// </summary>
        Level1Bgm = 7,
    }

} 

