
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Sound
{
public sealed partial class SoundConfig : Luban.BeanBase
{
    public SoundConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Key = _buf.ReadString();
        NameCn = _buf.ReadString();
        Desc = _buf.ReadString();
        LegacyId = _buf.ReadString();
        Group = _buf.ReadString();
        Path = _buf.ReadString();
    }

    public static SoundConfig DeserializeSoundConfig(ByteBuf _buf)
    {
        return new Sound.SoundConfig(_buf);
    }

    /// <summary>
    /// 音效ID(与 SoundId 枚举值一致)
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 枚举名(与 SoundId 一致,便于读表/搜索)
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 中文名
    /// </summary>
    public readonly string NameCn;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 旧音频文件名
    /// </summary>
    public readonly string LegacyId;
    /// <summary>
    /// 框架声音组名(Music/SFX/UI,对应 SoundGroupRes)
    /// </summary>
    public readonly string Group;
    /// <summary>
    /// 音频资源路径
    /// </summary>
    public readonly string Path;
   
    public const int __ID__ = 1536834194;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Key:" + Key + ","
        + "NameCn:" + NameCn + ","
        + "Desc:" + Desc + ","
        + "LegacyId:" + LegacyId + ","
        + "Group:" + Group + ","
        + "Path:" + Path + ","
        + "}";
    }
}
}

