
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Sound
{
public partial class TbSoundConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Sound.SoundConfig> _dataMap;
    private readonly System.Collections.Generic.List<Sound.SoundConfig> _dataList;
    
    public TbSoundConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Sound.SoundConfig>(n);
        _dataList = new System.Collections.Generic.List<Sound.SoundConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Sound.SoundConfig _v;
            _v = global::GameConfig.Sound.SoundConfig.DeserializeSoundConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Sound.SoundConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Sound.SoundConfig> DataList => _dataList;

    public Sound.SoundConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Sound.SoundConfig Get(int key) => _dataMap[key];
    public Sound.SoundConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

