
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Level
{
public sealed partial class LevelWaveConfig : Luban.BeanBase
{
    public LevelWaveConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        NameCn = _buf.ReadString();
        Desc = _buf.ReadString();
        LevelId = _buf.ReadInt();
        WaveIndex = _buf.ReadInt();
        TriggerX = _buf.ReadFloat();
    }

    public static LevelWaveConfig DeserializeLevelWaveConfig(ByteBuf _buf)
    {
        return new Level.LevelWaveConfig(_buf);
    }

    /// <summary>
    /// 波次ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 中文名
    /// </summary>
    public readonly string NameCn;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 关卡ID
    /// </summary>
    public readonly int LevelId;
    /// <summary>
    /// 波次序号(1起)
    /// </summary>
    public readonly int WaveIndex;
    /// <summary>
    /// 玩家 x 达到该值时触发本波
    /// </summary>
    public readonly float TriggerX;
   
    public const int __ID__ = 167509909;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "NameCn:" + NameCn + ","
        + "Desc:" + Desc + ","
        + "LevelId:" + LevelId + ","
        + "WaveIndex:" + WaveIndex + ","
        + "TriggerX:" + TriggerX + ","
        + "}";
    }
}
}

