
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Level
{
public sealed partial class LevelConfig : Luban.BeanBase
{
    public LevelConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LegacyId = _buf.ReadInt();
        NameCn = _buf.ReadString();
        Desc = _buf.ReadString();
        ScenePath = _buf.ReadString();
        BgmSoundId = (Sound.SoundId)_buf.ReadInt();
        MaxAlive = _buf.ReadInt();
        SpawnInterval = _buf.ReadFloat();
    }

    public static LevelConfig DeserializeLevelConfig(ByteBuf _buf)
    {
        return new Level.LevelConfig(_buf);
    }

    /// <summary>
    /// 关卡ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 旧关卡编号
    /// </summary>
    public readonly int LegacyId;
    /// <summary>
    /// 中文名
    /// </summary>
    public readonly string NameCn;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 关卡场景路径
    /// </summary>
    public readonly string ScenePath;
    /// <summary>
    /// 关卡背景音乐(SoundConfig;None=无;触发者在此,按 Configs/AGENTS.md 音效定稿)
    /// </summary>
    public readonly Sound.SoundId BgmSoundId;
    /// <summary>
    /// 场上怪物上限(旧项目全局硬编码6)
    /// </summary>
    public readonly int MaxAlive;
    /// <summary>
    /// 补怪间隔秒(旧设置默认1.2)
    /// </summary>
    public readonly float SpawnInterval;
   
    public const int __ID__ = 735472700;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "LegacyId:" + LegacyId + ","
        + "NameCn:" + NameCn + ","
        + "Desc:" + Desc + ","
        + "ScenePath:" + ScenePath + ","
        + "BgmSoundId:" + BgmSoundId + ","
        + "MaxAlive:" + MaxAlive + ","
        + "SpawnInterval:" + SpawnInterval + ","
        + "}";
    }
}
}

