
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Level
{
public sealed partial class LevelStage : Luban.BeanBase
{
    public LevelStage(ByteBuf _buf) 
    {
        StageOrder = _buf.ReadInt();
        StageName = _buf.ReadString();
        Activation = (Level.StageActivation)_buf.ReadInt();
        TriggerId = _buf.ReadString();
        GateId = _buf.ReadString();
        MaxActive = _buf.ReadInt();
        SpawnDelay = _buf.ReadFloat();
        {int n0 = _buf.ReadSize(); Recipes = new System.Collections.Generic.List<Level.LevelSpawnRecipe>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Level.LevelSpawnRecipe _e0;  _e0 = global::GameConfig.Level.LevelSpawnRecipe.DeserializeLevelSpawnRecipe(_buf); Recipes.Add(_e0);}}
    }

    public static LevelStage DeserializeLevelStage(ByteBuf _buf)
    {
        return new Level.LevelStage(_buf);
    }

    /// <summary>
    /// 从 1 连续递增，与阶段列表行序一致
    /// </summary>
    public readonly int StageOrder;
    /// <summary>
    /// 阶段名
    /// </summary>
    public readonly string StageName;
    /// <summary>
    /// CameraArrived=相机右缘抵达阶段右界；Trigger=特殊区域激活
    /// </summary>
    public readonly Level.StageActivation Activation;
    /// <summary>
    /// 仅 Trigger 阶段填写，其他阶段留空
    /// </summary>
    public readonly string TriggerId;
    /// <summary>
    /// 阶段右界门 ID；最后阶段可留空，使用关卡右墙
    /// </summary>
    public readonly string GateId;
    /// <summary>
    /// 最大并存数
    /// </summary>
    public readonly int MaxActive;
    /// <summary>
    /// 阶段启动后开始生成的延迟（秒），与各配方 Delay 相加
    /// </summary>
    public readonly float SpawnDelay;
    /// <summary>
    /// 同阶段配方并行；每行一条独立生成流
    /// </summary>
    public readonly System.Collections.Generic.List<Level.LevelSpawnRecipe> Recipes;
   
    public const int __ID__ = 592827076;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Recipes) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "StageOrder:" + StageOrder + ","
        + "StageName:" + StageName + ","
        + "Activation:" + Activation + ","
        + "TriggerId:" + TriggerId + ","
        + "GateId:" + GateId + ","
        + "MaxActive:" + MaxActive + ","
        + "SpawnDelay:" + SpawnDelay + ","
        + "Recipes:" + Luban.StringUtil.CollectionToString(Recipes) + ","
        + "}";
    }
}
}

