
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Level
{
public sealed partial class LevelStageConfig : Luban.BeanBase
{
    public LevelStageConfig(ByteBuf _buf) 
    {
        RowId = _buf.ReadInt();
        LevelId = _buf.ReadInt();
        StageOrder = _buf.ReadInt();
        Sequence = _buf.ReadInt();
        MonsterEntityId = (Entity.EntityId)_buf.ReadInt();
        SpawnPointId = _buf.ReadString();
        Count = _buf.ReadInt();
        Delay = _buf.ReadFloat();
        Interval = _buf.ReadFloat();
    }

    public static LevelStageConfig DeserializeLevelStageConfig(ByteBuf _buf)
    {
        return new Level.LevelStageConfig(_buf);
    }

    /// <summary>
    /// 稳定生成配方行ID
    /// </summary>
    public readonly int RowId;
    /// <summary>
    /// 关卡ID
    /// </summary>
    public readonly int LevelId;
    /// <summary>
    /// 阶段顺序（与 LevelConfig 对应）
    /// </summary>
    public readonly int StageOrder;
    /// <summary>
    /// 阶段内生成顺序
    /// </summary>
    public readonly int Sequence;
    /// <summary>
    /// 怪物实体枚举（便于查阅）
    /// </summary>
    public readonly Entity.EntityId MonsterEntityId;
    /// <summary>
    /// 场景生成点ID
    /// </summary>
    public readonly string SpawnPointId;
    /// <summary>
    /// 生成数量
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// 首次延迟秒
    /// </summary>
    public readonly float Delay;
    /// <summary>
    /// 生成间隔秒
    /// </summary>
    public readonly float Interval;
   
    public const int __ID__ = 1696210726;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "RowId:" + RowId + ","
        + "LevelId:" + LevelId + ","
        + "StageOrder:" + StageOrder + ","
        + "Sequence:" + Sequence + ","
        + "MonsterEntityId:" + MonsterEntityId + ","
        + "SpawnPointId:" + SpawnPointId + ","
        + "Count:" + Count + ","
        + "Delay:" + Delay + ","
        + "Interval:" + Interval + ","
        + "}";
    }
}
}

