
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Level
{
public sealed partial class LevelSpawnRecipe : Luban.BeanBase
{
    public LevelSpawnRecipe(ByteBuf _buf) 
    {
        MonsterEntityId = (Entity.EntityId)_buf.ReadInt();
        SpawnPointId = _buf.ReadString();
        Count = _buf.ReadInt();
        Delay = _buf.ReadFloat();
        Interval = _buf.ReadFloat();
    }

    public static LevelSpawnRecipe DeserializeLevelSpawnRecipe(ByteBuf _buf)
    {
        return new Level.LevelSpawnRecipe(_buf);
    }

    /// <summary>
    /// 可读怪物实体枚举；唯一关联怪物配置与实体资源
    /// </summary>
    public readonly Entity.EntityId MonsterEntityId;
    /// <summary>
    /// 场景生成点的稳定 ID
    /// </summary>
    public readonly string SpawnPointId;
    /// <summary>
    /// 生成数量
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// 首次延迟秒
    /// </summary>
    public readonly float Delay;
    /// <summary>
    /// 生成间隔秒
    /// </summary>
    public readonly float Interval;
   
    public const int __ID__ = 119935023;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "MonsterEntityId:" + MonsterEntityId + ","
        + "SpawnPointId:" + SpawnPointId + ","
        + "Count:" + Count + ","
        + "Delay:" + Delay + ","
        + "Interval:" + Interval + ","
        + "}";
    }
}
}

