
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Level
{
public sealed partial class LevelSpawnConfig : Luban.BeanBase
{
    public LevelSpawnConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        NameCn = _buf.ReadString();
        Desc = _buf.ReadString();
        WaveId = _buf.ReadInt();
        MonsterId = _buf.ReadInt();
        X = _buf.ReadFloat();
        Y = _buf.ReadFloat();
    }

    public static LevelSpawnConfig DeserializeLevelSpawnConfig(ByteBuf _buf)
    {
        return new Level.LevelSpawnConfig(_buf);
    }

    /// <summary>
    /// 刷怪点ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 中文名
    /// </summary>
    public readonly string NameCn;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 波次ID(LevelWaveConfig.Id)
    /// </summary>
    public readonly int WaveId;
    /// <summary>
    /// 怪物ID(MonsterConfig.Id;M6 垂直切片全用花果山猴子,旧 Monster_2/3 迁入后改回)
    /// </summary>
    public readonly int MonsterId;
    /// <summary>
    /// 出生坐标 x(旧 Monster_position_x)
    /// </summary>
    public readonly float X;
    /// <summary>
    /// 出生坐标 y(旧 Monster_position_y)
    /// </summary>
    public readonly float Y;
   
    public const int __ID__ = -299942429;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "NameCn:" + NameCn + ","
        + "Desc:" + Desc + ","
        + "WaveId:" + WaveId + ","
        + "MonsterId:" + MonsterId + ","
        + "X:" + X + ","
        + "Y:" + Y + ","
        + "}";
    }
}
}

