
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Level
{
public sealed partial class LevelConfig : Luban.BeanBase
{
    public LevelConfig(ByteBuf _buf) 
    {
        LevelId = _buf.ReadInt();
        LegacyId = _buf.ReadInt();
        NameCn = _buf.ReadString();
        Desc = _buf.ReadString();
        ScenePath = _buf.ReadString();
        PlayerSpawnPointId = _buf.ReadString();
        {int n0 = _buf.ReadSize(); Stages = new System.Collections.Generic.List<Level.LevelStage>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Level.LevelStage _e0;  _e0 = global::GameConfig.Level.LevelStage.DeserializeLevelStage(_buf); Stages.Add(_e0);}}
    }

    public static LevelConfig DeserializeLevelConfig(ByteBuf _buf)
    {
        return new Level.LevelConfig(_buf);
    }

    /// <summary>
    /// 关卡ID（主键）
    /// </summary>
    public readonly int LevelId;
    /// <summary>
    /// 旧项目关卡编号
    /// </summary>
    public readonly int LegacyId;
    /// <summary>
    /// 关卡名
    /// </summary>
    public readonly string NameCn;
    /// <summary>
    /// 关卡说明
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 场景资源路径
    /// </summary>
    public readonly string ScenePath;
    /// <summary>
    /// 玩家出生点ID
    /// </summary>
    public readonly string PlayerSpawnPointId;
    /// <summary>
    /// 阶段列表（多行：每行一个阶段；配方续行阶段列留空）
    /// </summary>
    public readonly System.Collections.Generic.List<Level.LevelStage> Stages;
   
    public const int __ID__ = 735472700;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Stages) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "LevelId:" + LevelId + ","
        + "LegacyId:" + LegacyId + ","
        + "NameCn:" + NameCn + ","
        + "Desc:" + Desc + ","
        + "ScenePath:" + ScenePath + ","
        + "PlayerSpawnPointId:" + PlayerSpawnPointId + ","
        + "Stages:" + Luban.StringUtil.CollectionToString(Stages) + ","
        + "}";
    }
}
}

