
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Level
{ 
    public enum StageClearPolicy
    {
        /// <summary>
        /// 清除全部活跃怪物
        /// </summary>
        KillAll = 0,
    }

} 

