
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Level
{ 
    public enum StageActivation
    {
        /// <summary>
        /// 相机抵达阶段右界
        /// </summary>
        CameraArrived = 0,
        /// <summary>
        /// 特殊区域激活
        /// </summary>
        Trigger = 1,
    }

} 

