
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Level
{ 
    public enum StageActivation
    {
        /// <summary>
        /// 进入关卡
        /// </summary>
        OnEnter = 0,
        /// <summary>
        /// 触发器
        /// </summary>
        Trigger = 1,
        /// <summary>
        /// 前阶段清除
        /// </summary>
        OnClear = 2,
    }

} 

