
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Level
{
public partial class TbLevelSpawnConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Level.LevelSpawnConfig> _dataMap;
    private readonly System.Collections.Generic.List<Level.LevelSpawnConfig> _dataList;
    
    public TbLevelSpawnConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Level.LevelSpawnConfig>(n);
        _dataList = new System.Collections.Generic.List<Level.LevelSpawnConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Level.LevelSpawnConfig _v;
            _v = global::GameConfig.Level.LevelSpawnConfig.DeserializeLevelSpawnConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Level.LevelSpawnConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Level.LevelSpawnConfig> DataList => _dataList;

    public Level.LevelSpawnConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Level.LevelSpawnConfig Get(int key) => _dataMap[key];
    public Level.LevelSpawnConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

