
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Level
{
public partial class TbLevelConfig
{
    private readonly System.Collections.Generic.List<Level.LevelConfig> _dataList;


    public TbLevelConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataList = new System.Collections.Generic.List<Level.LevelConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Level.LevelConfig _v;
            _v = global::GameConfig.Level.LevelConfig.DeserializeLevelConfig(_buf);
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<Level.LevelConfig> DataList => _dataList;

    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

