
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Level
{
public partial class TbLevelStageConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Level.LevelStageConfig> _dataMap;
    private readonly System.Collections.Generic.List<Level.LevelStageConfig> _dataList;
    
    public TbLevelStageConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Level.LevelStageConfig>(n);
        _dataList = new System.Collections.Generic.List<Level.LevelStageConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Level.LevelStageConfig _v;
            _v = global::GameConfig.Level.LevelStageConfig.DeserializeLevelStageConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.RowId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Level.LevelStageConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Level.LevelStageConfig> DataList => _dataList;

    public Level.LevelStageConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Level.LevelStageConfig Get(int key) => _dataMap[key];
    public Level.LevelStageConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

