
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Hero
{
public sealed partial class HeroConfig : Luban.BeanBase
{
    public HeroConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LegacyId = _buf.ReadInt();
        NameCn = _buf.ReadString();
        Desc = _buf.ReadString();
        EntityId = (Entity.EntityId)_buf.ReadInt();
        BaseHp = _buf.ReadInt();
        BaseMp = _buf.ReadInt();
        BasePower = _buf.ReadInt();
        BaseDef = _buf.ReadInt();
        BaseMdef = _buf.ReadInt();
        GrowHp = _buf.ReadInt();
        GrowMp = _buf.ReadInt();
        GrowPower = _buf.ReadInt();
        GrowDef = _buf.ReadInt();
        GrowMdef = _buf.ReadInt();
        Crit = _buf.ReadInt();
        Miss = _buf.ReadInt();
        Lucky = _buf.ReadInt();
        Toughness = _buf.ReadInt();
        Htarget = _buf.ReadInt();
        CritReduce = _buf.ReadInt();
        Ar = _buf.ReadInt();
        Sp = _buf.ReadInt();
        Vampirism = _buf.ReadFloat();
        RHp = _buf.ReadFloat();
        RMp = _buf.ReadFloat();
        WalkSpeed = _buf.ReadFloat();
        RunSpeed = _buf.ReadFloat();
        RunDoubleTapWindow = _buf.ReadFloat();
        IdleEmoteDelay = GameLogic.Config.ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        JumpSpeed = _buf.ReadFloat();
        Gravity = _buf.ReadFloat();
        JumpCountMax = _buf.ReadInt();
        HurtSoundId = (Sound.SoundId)_buf.ReadInt();
        DeathSoundId = (Sound.SoundId)_buf.ReadInt();
    }

    public static HeroConfig DeserializeHeroConfig(ByteBuf _buf)
    {
        return new Hero.HeroConfig(_buf);
    }

    /// <summary>
    /// 英雄ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 旧 role 编号
    /// </summary>
    public readonly int LegacyId;
    /// <summary>
    /// 中文名
    /// </summary>
    public readonly string NameCn;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 实体枚举
    /// </summary>
    public readonly Entity.EntityId EntityId;
    /// <summary>
    /// 1级生命(旧 SHp)
    /// </summary>
    public readonly int BaseHp;
    /// <summary>
    /// 1级魔法(旧 SMp)
    /// </summary>
    public readonly int BaseMp;
    /// <summary>
    /// 1级攻击
    /// </summary>
    public readonly int BasePower;
    /// <summary>
    /// 1级物防
    /// </summary>
    public readonly int BaseDef;
    /// <summary>
    /// 1级魔防
    /// </summary>
    public readonly int BaseMdef;
    /// <summary>
    /// 每级生命成长
    /// </summary>
    public readonly int GrowHp;
    /// <summary>
    /// 每级魔法成长
    /// </summary>
    public readonly int GrowMp;
    /// <summary>
    /// 每级攻击成长
    /// </summary>
    public readonly int GrowPower;
    /// <summary>
    /// 每级物防成长
    /// </summary>
    public readonly int GrowDef;
    /// <summary>
    /// 每级魔防成长
    /// </summary>
    public readonly int GrowMdef;
    /// <summary>
    /// 暴击
    /// </summary>
    public readonly int Crit;
    /// <summary>
    /// 闪避
    /// </summary>
    public readonly int Miss;
    /// <summary>
    /// 幸运
    /// </summary>
    public readonly int Lucky;
    /// <summary>
    /// 韧性(减对方幸运)
    /// </summary>
    public readonly int Toughness;
    /// <summary>
    /// 命中(破闪)
    /// </summary>
    public readonly int Htarget;
    /// <summary>
    /// 暴击抵抗
    /// </summary>
    public readonly int CritReduce;
    /// <summary>
    /// 破甲(减对方物防)
    /// </summary>
    public readonly int Ar;
    /// <summary>
    /// 破魔(减对方魔防)
    /// </summary>
    public readonly int Sp;
    /// <summary>
    /// 吸血系数(物理伤害转化回血)
    /// </summary>
    public readonly float Vampirism;
    /// <summary>
    /// 每秒回血
    /// </summary>
    public readonly float RHp;
    /// <summary>
    /// 每秒回魔
    /// </summary>
    public readonly float RMp;
    /// <summary>
    /// 慢走速度 px/s
    /// </summary>
    public readonly float WalkSpeed;
    /// <summary>
    /// 跑步(快走)速度 px/s
    /// </summary>
    public readonly float RunSpeed;
    /// <summary>
    /// 双击方向键进入跑步的判定窗口(秒)
    /// </summary>
    public readonly float RunDoubleTapWindow;
    /// <summary>
    /// 待机后隔多久随机播一次憨笑(秒,x=最短,y=最长,写法 6,12)
    /// </summary>
    public readonly Godot.Vector2 IdleEmoteDelay;
    /// <summary>
    /// 起跳速度(向上为正,旧 jump_power=-540)
    /// </summary>
    public readonly float JumpSpeed;
    /// <summary>
    /// 重力(旧 gravity=980 向下)
    /// </summary>
    public readonly float Gravity;
    /// <summary>
    /// 最多跳跃次数(含地面一段与空中段,旧 jump_count&lt;2 判据)
    /// </summary>
    public readonly int JumpCountMax;
    /// <summary>
    /// 受击语音(自己挨打时的声音,None=无;按受害者选音,BaseHero.gd:592)
    /// </summary>
    public readonly Sound.SoundId HurtSoundId;
    /// <summary>
    /// 死亡语音(None=无)
    /// </summary>
    public readonly Sound.SoundId DeathSoundId;
   
    public const int __ID__ = -1911300528;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "LegacyId:" + LegacyId + ","
        + "NameCn:" + NameCn + ","
        + "Desc:" + Desc + ","
        + "EntityId:" + EntityId + ","
        + "BaseHp:" + BaseHp + ","
        + "BaseMp:" + BaseMp + ","
        + "BasePower:" + BasePower + ","
        + "BaseDef:" + BaseDef + ","
        + "BaseMdef:" + BaseMdef + ","
        + "GrowHp:" + GrowHp + ","
        + "GrowMp:" + GrowMp + ","
        + "GrowPower:" + GrowPower + ","
        + "GrowDef:" + GrowDef + ","
        + "GrowMdef:" + GrowMdef + ","
        + "Crit:" + Crit + ","
        + "Miss:" + Miss + ","
        + "Lucky:" + Lucky + ","
        + "Toughness:" + Toughness + ","
        + "Htarget:" + Htarget + ","
        + "CritReduce:" + CritReduce + ","
        + "Ar:" + Ar + ","
        + "Sp:" + Sp + ","
        + "Vampirism:" + Vampirism + ","
        + "RHp:" + RHp + ","
        + "RMp:" + RMp + ","
        + "WalkSpeed:" + WalkSpeed + ","
        + "RunSpeed:" + RunSpeed + ","
        + "RunDoubleTapWindow:" + RunDoubleTapWindow + ","
        + "IdleEmoteDelay:" + IdleEmoteDelay + ","
        + "JumpSpeed:" + JumpSpeed + ","
        + "Gravity:" + Gravity + ","
        + "JumpCountMax:" + JumpCountMax + ","
        + "HurtSoundId:" + HurtSoundId + ","
        + "DeathSoundId:" + DeathSoundId + ","
        + "}";
    }
}
}

