
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Hero
{
public sealed partial class HeroAttackConfig : Luban.BeanBase
{
    public HeroAttackConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        NameCn = _buf.ReadString();
        Desc = _buf.ReadString();
        HeroId = _buf.ReadInt();
        ComboIndex = _buf.ReadInt();
        AttackId = _buf.ReadInt();
    }

    public static HeroAttackConfig DeserializeHeroAttackConfig(ByteBuf _buf)
    {
        return new Hero.HeroAttackConfig(_buf);
    }

    /// <summary>
    /// 连段记录ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 中文名
    /// </summary>
    public readonly string NameCn;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 英雄ID
    /// </summary>
    public readonly int HeroId;
    /// <summary>
    /// 连段序号(0起)
    /// </summary>
    public readonly int ComboIndex;
    /// <summary>
    /// 攻击ID(AttackConfig.Id)
    /// </summary>
    public readonly int AttackId;
   
    public const int __ID__ = 764731448;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "NameCn:" + NameCn + ","
        + "Desc:" + Desc + ","
        + "HeroId:" + HeroId + ","
        + "ComboIndex:" + ComboIndex + ","
        + "AttackId:" + AttackId + ","
        + "}";
    }
}
}

