
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Hero
{
/// <summary>
/// 英雄逐级属性（HeroId + Level 联合主键）
/// </summary>
public sealed partial class HeroGrowthConfig : Luban.BeanBase
{
    public HeroGrowthConfig(ByteBuf _buf) 
    {
        HeroId = _buf.ReadInt();
        Level = _buf.ReadInt();
        Stats = global::GameConfig.Stat.StatBlock.DeserializeStatBlock(_buf);
    }

    public static HeroGrowthConfig DeserializeHeroGrowthConfig(ByteBuf _buf)
    {
        return new Hero.HeroGrowthConfig(_buf);
    }

    /// <summary>
    /// 英雄ID(对应 HeroConfig.Id)
    /// </summary>
    public readonly int HeroId;
    /// <summary>
    /// 等级(1 起连续，覆盖经验表全部等级)
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 该等级的成长属性
    /// </summary>
    public readonly Stat.StatBlock Stats;
   
    public const int __ID__ = 1906899063;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Stats?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "HeroId:" + HeroId + ","
        + "Level:" + Level + ","
        + "Stats:" + Stats + ","
        + "}";
    }
}
}

