
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Hero
{
public sealed partial class HeroLevelConfig : Luban.BeanBase
{
    public HeroLevelConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        NameCn = _buf.ReadString();
        Desc = _buf.ReadString();
        MaxExp = _buf.ReadInt();
    }

    public static HeroLevelConfig DeserializeHeroLevelConfig(ByteBuf _buf)
    {
        return new Hero.HeroLevelConfig(_buf);
    }

    /// <summary>
    /// 等级(即ID)
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 等级名
    /// </summary>
    public readonly string NameCn;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 升到下一级所需经验(旧 max_exp)
    /// </summary>
    public readonly int MaxExp;
   
    public const int __ID__ = -181619304;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "NameCn:" + NameCn + ","
        + "Desc:" + Desc + ","
        + "MaxExp:" + MaxExp + ","
        + "}";
    }
}
}

