
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Hero
{
public sealed partial class HeroConfig : Luban.BeanBase
{
    public HeroConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LegacyId = _buf.ReadInt();
        NameCn = _buf.ReadString();
        Desc = _buf.ReadString();
        EntityId = (Entity.EntityId)_buf.ReadInt();
        WalkSpeed = _buf.ReadFloat();
        RunSpeed = _buf.ReadFloat();
        RunDoubleTapWindow = _buf.ReadFloat();
        IdleEmoteDelay = GameLogic.Config.ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        JumpSpeed = _buf.ReadFloat();
        Gravity = _buf.ReadFloat();
        JumpCountMax = _buf.ReadInt();
        HurtSoundId = (Sound.SoundId)_buf.ReadInt();
        DeathSoundId = (Sound.SoundId)_buf.ReadInt();
        InputBufferTime = _buf.ReadFloat();
    }

    public static HeroConfig DeserializeHeroConfig(ByteBuf _buf)
    {
        return new Hero.HeroConfig(_buf);
    }

    /// <summary>
    /// 英雄ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 旧 role 编号
    /// </summary>
    public readonly int LegacyId;
    /// <summary>
    /// 中文名
    /// </summary>
    public readonly string NameCn;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 实体枚举
    /// </summary>
    public readonly Entity.EntityId EntityId;
    /// <summary>
    /// 慢走速度 px/s
    /// </summary>
    public readonly float WalkSpeed;
    /// <summary>
    /// 跑步(快走)速度 px/s
    /// </summary>
    public readonly float RunSpeed;
    /// <summary>
    /// 双击方向键进入跑步的判定窗口(秒)
    /// </summary>
    public readonly float RunDoubleTapWindow;
    /// <summary>
    /// 待机后隔多久随机播一次憨笑(秒,x=最短,y=最长,写法 6,12)
    /// </summary>
    public readonly Godot.Vector2 IdleEmoteDelay;
    /// <summary>
    /// 起跳速度(向上为正,旧 jump_power=-540)
    /// </summary>
    public readonly float JumpSpeed;
    /// <summary>
    /// 重力(旧 gravity=980 向下)
    /// </summary>
    public readonly float Gravity;
    /// <summary>
    /// 最多跳跃次数(含地面一段与空中段,旧 jump_count&lt;2 判据)
    /// </summary>
    public readonly int JumpCountMax;
    /// <summary>
    /// 受击语音(自己挨打时的声音,None=无;按受害者选音,BaseHero.gd:592)
    /// </summary>
    public readonly Sound.SoundId HurtSoundId;
    /// <summary>
    /// 死亡语音(None=无)
    /// </summary>
    public readonly Sound.SoundId DeathSoundId;
    /// <summary>
    /// 输入缓冲秒:跳跃/普攻按键在这段时间内等到可执行时机仍生效(0=只在按下那一帧有效)
    /// </summary>
    public readonly float InputBufferTime;
   
    public const int __ID__ = -1911300528;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "LegacyId:" + LegacyId + ","
        + "NameCn:" + NameCn + ","
        + "Desc:" + Desc + ","
        + "EntityId:" + EntityId + ","
        + "WalkSpeed:" + WalkSpeed + ","
        + "RunSpeed:" + RunSpeed + ","
        + "RunDoubleTapWindow:" + RunDoubleTapWindow + ","
        + "IdleEmoteDelay:" + IdleEmoteDelay + ","
        + "JumpSpeed:" + JumpSpeed + ","
        + "Gravity:" + Gravity + ","
        + "JumpCountMax:" + JumpCountMax + ","
        + "HurtSoundId:" + HurtSoundId + ","
        + "DeathSoundId:" + DeathSoundId + ","
        + "InputBufferTime:" + InputBufferTime + ","
        + "}";
    }
}
}

