
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Hero
{
public partial class TbHeroConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Hero.HeroConfig> _dataMap;
    private readonly System.Collections.Generic.List<Hero.HeroConfig> _dataList;
    
    public TbHeroConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Hero.HeroConfig>(n);
        _dataList = new System.Collections.Generic.List<Hero.HeroConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Hero.HeroConfig _v;
            _v = global::GameConfig.Hero.HeroConfig.DeserializeHeroConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Hero.HeroConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Hero.HeroConfig> DataList => _dataList;

    public Hero.HeroConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Hero.HeroConfig Get(int key) => _dataMap[key];
    public Hero.HeroConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

