
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Hero
{
public partial class TbHeroAttackConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Hero.HeroAttackConfig> _dataMap;
    private readonly System.Collections.Generic.List<Hero.HeroAttackConfig> _dataList;
    
    public TbHeroAttackConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Hero.HeroAttackConfig>(n);
        _dataList = new System.Collections.Generic.List<Hero.HeroAttackConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Hero.HeroAttackConfig _v;
            _v = global::GameConfig.Hero.HeroAttackConfig.DeserializeHeroAttackConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Hero.HeroAttackConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Hero.HeroAttackConfig> DataList => _dataList;

    public Hero.HeroAttackConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Hero.HeroAttackConfig Get(int key) => _dataMap[key];
    public Hero.HeroAttackConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

