
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Hero
{
public partial class TbHeroGrowthConfig
{
    private readonly System.Collections.Generic.List<Hero.HeroGrowthConfig> _dataList;

    private System.Collections.Generic.Dictionary<(int, int), Hero.HeroGrowthConfig> _dataMapUnion;

    public TbHeroGrowthConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataList = new System.Collections.Generic.List<Hero.HeroGrowthConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Hero.HeroGrowthConfig _v;
            _v = global::GameConfig.Hero.HeroGrowthConfig.DeserializeHeroGrowthConfig(_buf);
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(int, int), Hero.HeroGrowthConfig>(n);
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.HeroId, _v.Level), _v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<Hero.HeroGrowthConfig> DataList => _dataList;

    public Hero.HeroGrowthConfig Get(int HeroId, int Level) => _dataMapUnion.TryGetValue((HeroId, Level), out Hero.HeroGrowthConfig __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

