
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Monster
{
/// <summary>
/// 怪物配置（怪物无成长，Level 只用于等级压制）
/// </summary>
public sealed partial class MonsterConfig : Luban.BeanBase
{
    public MonsterConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LegacyId = _buf.ReadInt();
        NameCn = _buf.ReadString();
        Desc = _buf.ReadString();
        EntityId = (Entity.EntityId)_buf.ReadInt();
        Level = _buf.ReadInt();
        Stats = global::GameConfig.Stat.StatBlock.DeserializeStatBlock(_buf);
        MoveSpeed = _buf.ReadFloat();
        SightRange = _buf.ReadInt();
        AttackDesire = _buf.ReadInt();
        BehitCalmTime = _buf.ReadFloat();
        AddExp = _buf.ReadInt();
        HurtSoundId = (Sound.SoundId)_buf.ReadInt();
        DeathSoundId = (Sound.SoundId)_buf.ReadInt();
        Gravity = _buf.ReadFloat();
        PatrolInterval = _buf.ReadFloat();
        PatrolIdleChance = _buf.ReadInt();
        PatrolRadius = _buf.ReadInt();
        AttackInterval = _buf.ReadFloat();
        AttackFirstDelay = GameLogic.Config.ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        Rank = (Monster.MonsterRank)_buf.ReadInt();
        SuperArmor = _buf.ReadBool();
        AttackRangeSlack = _buf.ReadInt();
        LoseTargetTime = _buf.ReadFloat();
        PaceRange = _buf.ReadInt();
    }

    public static MonsterConfig DeserializeMonsterConfig(ByteBuf _buf)
    {
        return new Monster.MonsterConfig(_buf);
    }

    /// <summary>
    /// 怪物ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 旧怪物编号
    /// </summary>
    public readonly int LegacyId;
    /// <summary>
    /// 中文名
    /// </summary>
    public readonly string NameCn;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 实体枚举
    /// </summary>
    public readonly Entity.EntityId EntityId;
    /// <summary>
    /// 等级(参与等级压制)
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 战斗属性(攻击 Power 填 0：怪物伤害由招式 FlatPower 决定)
    /// </summary>
    public readonly Stat.StatBlock Stats;
    /// <summary>
    /// 移动速度 px/s(旧 speed=8,代码里&#215;10)
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 索敌距离(旧 mysee)
    /// </summary>
    public readonly int SightRange;
    /// <summary>
    /// 攻击欲望 0-100(旧 attackDesire)
    /// </summary>
    public readonly int AttackDesire;
    /// <summary>
    /// 受击后僵直秒数(旧 behit_calmtime)
    /// </summary>
    public readonly float BehitCalmTime;
    /// <summary>
    /// 击杀给英雄的经验(旧 add_exp)
    /// </summary>
    public readonly int AddExp;
    /// <summary>
    /// 受击语音(旧项目怪物无语音素材,填 None;M5 用)
    /// </summary>
    public readonly Sound.SoundId HurtSoundId;
    /// <summary>
    /// 死亡语音(同上)
    /// </summary>
    public readonly Sound.SoundId DeathSoundId;
    /// <summary>
    /// 重力 px/s&#178;(旧 gravity=980 向下)
    /// </summary>
    public readonly float Gravity;
    /// <summary>
    /// 巡逻重新决策间隔秒(旧 change_state 计时器 3s)
    /// </summary>
    public readonly float PatrolInterval;
    /// <summary>
    /// 巡逻决策时原地停留概率 0-100(旧 ran_num&lt;10),其余左右各半
    /// </summary>
    public readonly int PatrolIdleChance;
    /// <summary>
    /// 巡逻半径 px:离出生点超出即折返(新增,旧项目无,防走出场地)
    /// </summary>
    public readonly int PatrolRadius;
    /// <summary>
    /// 近身后普攻判定间隔秒(旧 count%60≈1s,每次按 AttackDesire 掷骰)
    /// </summary>
    public readonly float AttackInterval;
    /// <summary>
    /// 进入攻击范围后首次出手判定的随机延迟秒(x=最短,y=最长);出手是概率判定,这里只是反应时间
    /// </summary>
    public readonly Godot.Vector2 AttackFirstDelay;
    /// <summary>
    /// 阶级 Normal/Elite/Boss(旧 is_boss;供 HUD/掉落/结算区分)
    /// </summary>
    public readonly Monster.MonsterRank Rank;
    /// <summary>
    /// 霸体:受击不硬直不击退、不打断出招(旧 IsSuperArmor/Monster_18 类保护)
    /// </summary>
    public readonly bool SuperArmor;
    /// <summary>
    /// 站定滞回 px:目标离开普攻判定盒水平范围超过本值才重新追击(防目标被击退几像素就来回切换)
    /// </summary>
    public readonly int AttackRangeSlack;
    /// <summary>
    /// 丢失目标秒:目标水平距离持续超出 SightRange 这么久即放弃、回去巡逻(0=永不丢失)
    /// </summary>
    public readonly float LoseTargetTime;
    /// <summary>
    /// 踱步半幅 px:目标在头顶/平台上够不着时,以目标 x 为中心左右来回走的距离(0=原地等)
    /// </summary>
    public readonly int PaceRange;
   
    public const int __ID__ = 129443944;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Stats?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "LegacyId:" + LegacyId + ","
        + "NameCn:" + NameCn + ","
        + "Desc:" + Desc + ","
        + "EntityId:" + EntityId + ","
        + "Level:" + Level + ","
        + "Stats:" + Stats + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "SightRange:" + SightRange + ","
        + "AttackDesire:" + AttackDesire + ","
        + "BehitCalmTime:" + BehitCalmTime + ","
        + "AddExp:" + AddExp + ","
        + "HurtSoundId:" + HurtSoundId + ","
        + "DeathSoundId:" + DeathSoundId + ","
        + "Gravity:" + Gravity + ","
        + "PatrolInterval:" + PatrolInterval + ","
        + "PatrolIdleChance:" + PatrolIdleChance + ","
        + "PatrolRadius:" + PatrolRadius + ","
        + "AttackInterval:" + AttackInterval + ","
        + "AttackFirstDelay:" + AttackFirstDelay + ","
        + "Rank:" + Rank + ","
        + "SuperArmor:" + SuperArmor + ","
        + "AttackRangeSlack:" + AttackRangeSlack + ","
        + "LoseTargetTime:" + LoseTargetTime + ","
        + "PaceRange:" + PaceRange + ","
        + "}";
    }
}
}

