
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Monster
{
public sealed partial class MonsterConfig : Luban.BeanBase
{
    public MonsterConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LegacyId = _buf.ReadInt();
        NameCn = _buf.ReadString();
        Desc = _buf.ReadString();
        EntityId = (Entity.EntityId)_buf.ReadInt();
        Level = _buf.ReadInt();
        Hp = _buf.ReadInt();
        Def = _buf.ReadInt();
        Mdef = _buf.ReadInt();
        Crit = _buf.ReadInt();
        Miss = _buf.ReadInt();
        Lucky = _buf.ReadInt();
        Toughness = _buf.ReadInt();
        Htarget = _buf.ReadInt();
        CritReduce = _buf.ReadInt();
        Ar = _buf.ReadInt();
        Sp = _buf.ReadInt();
        RHp = _buf.ReadFloat();
        MoveSpeed = _buf.ReadFloat();
        SightRange = _buf.ReadInt();
        AttackDesire = _buf.ReadInt();
        BehitCalmTime = _buf.ReadFloat();
        AddExp = _buf.ReadInt();
        HurtSoundId = (Sound.SoundId)_buf.ReadInt();
        DeathSoundId = (Sound.SoundId)_buf.ReadInt();
        Gravity = _buf.ReadFloat();
        PatrolInterval = _buf.ReadFloat();
        PatrolIdleChance = _buf.ReadInt();
        PatrolRadius = _buf.ReadInt();
        AttackInterval = _buf.ReadFloat();
        Rank = (Monster.MonsterRank)_buf.ReadInt();
        SuperArmor = _buf.ReadBool();
        AttackRangeSlack = _buf.ReadInt();
        LoseTargetTime = _buf.ReadFloat();
        PaceRange = _buf.ReadInt();
    }

    public static MonsterConfig DeserializeMonsterConfig(ByteBuf _buf)
    {
        return new Monster.MonsterConfig(_buf);
    }

    /// <summary>
    /// 怪物ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 旧怪物编号
    /// </summary>
    public readonly int LegacyId;
    /// <summary>
    /// 中文名
    /// </summary>
    public readonly string NameCn;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 实体枚举
    /// </summary>
    public readonly Entity.EntityId EntityId;
    /// <summary>
    /// 等级(参与等级压制)
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 生命(旧 SHp)
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 物防
    /// </summary>
    public readonly int Def;
    /// <summary>
    /// 魔防
    /// </summary>
    public readonly int Mdef;
    /// <summary>
    /// 暴击
    /// </summary>
    public readonly int Crit;
    /// <summary>
    /// 闪避
    /// </summary>
    public readonly int Miss;
    /// <summary>
    /// 幸运
    /// </summary>
    public readonly int Lucky;
    /// <summary>
    /// 韧性(减对方幸运)
    /// </summary>
    public readonly int Toughness;
    /// <summary>
    /// 命中(破闪)
    /// </summary>
    public readonly int Htarget;
    /// <summary>
    /// 暴击抵抗
    /// </summary>
    public readonly int CritReduce;
    /// <summary>
    /// 破甲(减对方物防)
    /// </summary>
    public readonly int Ar;
    /// <summary>
    /// 破魔(减对方魔防)
    /// </summary>
    public readonly int Sp;
    /// <summary>
    /// 每秒回血(旧 self_rhp)
    /// </summary>
    public readonly float RHp;
    /// <summary>
    /// 移动速度 px/s(旧 speed=8,代码里&#215;10)
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 索敌距离(旧 mysee)
    /// </summary>
    public readonly int SightRange;
    /// <summary>
    /// 攻击欲望 0-100(旧 attackDesire)
    /// </summary>
    public readonly int AttackDesire;
    /// <summary>
    /// 受击后僵直秒数(旧 behit_calmtime)
    /// </summary>
    public readonly float BehitCalmTime;
    /// <summary>
    /// 击杀给英雄的经验(旧 add_exp)
    /// </summary>
    public readonly int AddExp;
    /// <summary>
    /// 受击语音(旧项目怪物无语音素材,填 None;M5 用)
    /// </summary>
    public readonly Sound.SoundId HurtSoundId;
    /// <summary>
    /// 死亡语音(同上)
    /// </summary>
    public readonly Sound.SoundId DeathSoundId;
    /// <summary>
    /// 重力 px/s&#178;(旧 gravity=980 向下)
    /// </summary>
    public readonly float Gravity;
    /// <summary>
    /// 巡逻重新决策间隔秒(旧 change_state 计时器 2s)
    /// </summary>
    public readonly float PatrolInterval;
    /// <summary>
    /// 巡逻决策时原地停留概率 0-100(旧 ran_num&lt;10),其余左右各半
    /// </summary>
    public readonly int PatrolIdleChance;
    /// <summary>
    /// 巡逻半径 px:离出生点超出即折返(新增,旧项目无,防走出场地)
    /// </summary>
    public readonly int PatrolRadius;
    /// <summary>
    /// 近身后普攻判定间隔秒(旧 count%60≈1s,每次按 AttackDesire 掷骰)
    /// </summary>
    public readonly float AttackInterval;
    /// <summary>
    /// 阶级 Normal/Elite/Boss(旧 is_boss;供 HUD/掉落/结算区分)
    /// </summary>
    public readonly Monster.MonsterRank Rank;
    /// <summary>
    /// 霸体:受击不硬直不击退、不打断出招(旧 IsSuperArmor/Monster_18 类保护)
    /// </summary>
    public readonly bool SuperArmor;
    /// <summary>
    /// 站定滞回 px:目标离开普攻判定盒水平范围超过本值才重新追击(防目标被击退几像素就来回切换)
    /// </summary>
    public readonly int AttackRangeSlack;
    /// <summary>
    /// 丢失目标秒:目标水平距离持续超出 SightRange 这么久即放弃、回去巡逻(0=永不丢失)
    /// </summary>
    public readonly float LoseTargetTime;
    /// <summary>
    /// 踱步半幅 px:目标在头顶/平台上够不着时,以目标 x 为中心左右来回走的距离(0=原地等)
    /// </summary>
    public readonly int PaceRange;
   
    public const int __ID__ = 129443944;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "LegacyId:" + LegacyId + ","
        + "NameCn:" + NameCn + ","
        + "Desc:" + Desc + ","
        + "EntityId:" + EntityId + ","
        + "Level:" + Level + ","
        + "Hp:" + Hp + ","
        + "Def:" + Def + ","
        + "Mdef:" + Mdef + ","
        + "Crit:" + Crit + ","
        + "Miss:" + Miss + ","
        + "Lucky:" + Lucky + ","
        + "Toughness:" + Toughness + ","
        + "Htarget:" + Htarget + ","
        + "CritReduce:" + CritReduce + ","
        + "Ar:" + Ar + ","
        + "Sp:" + Sp + ","
        + "RHp:" + RHp + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "SightRange:" + SightRange + ","
        + "AttackDesire:" + AttackDesire + ","
        + "BehitCalmTime:" + BehitCalmTime + ","
        + "AddExp:" + AddExp + ","
        + "HurtSoundId:" + HurtSoundId + ","
        + "DeathSoundId:" + DeathSoundId + ","
        + "Gravity:" + Gravity + ","
        + "PatrolInterval:" + PatrolInterval + ","
        + "PatrolIdleChance:" + PatrolIdleChance + ","
        + "PatrolRadius:" + PatrolRadius + ","
        + "AttackInterval:" + AttackInterval + ","
        + "Rank:" + Rank + ","
        + "SuperArmor:" + SuperArmor + ","
        + "AttackRangeSlack:" + AttackRangeSlack + ","
        + "LoseTargetTime:" + LoseTargetTime + ","
        + "PaceRange:" + PaceRange + ","
        + "}";
    }
}
}

