
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Monster
{
public sealed partial class MonsterAttackConfig : Luban.BeanBase
{
    public MonsterAttackConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        NameCn = _buf.ReadString();
        Desc = _buf.ReadString();
        MonsterId = _buf.ReadInt();
        AttackId = _buf.ReadInt();
        Weight = _buf.ReadInt();
    }

    public static MonsterAttackConfig DeserializeMonsterAttackConfig(ByteBuf _buf)
    {
        return new Monster.MonsterAttackConfig(_buf);
    }

    /// <summary>
    /// 关联记录ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 中文名
    /// </summary>
    public readonly string NameCn;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 怪物ID
    /// </summary>
    public readonly int MonsterId;
    /// <summary>
    /// 攻击ID(AttackConfig.Id)
    /// </summary>
    public readonly int AttackId;
    /// <summary>
    /// AI 选择该攻击的权重
    /// </summary>
    public readonly int Weight;
   
    public const int __ID__ = 598620240;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "NameCn:" + NameCn + ","
        + "Desc:" + Desc + ","
        + "MonsterId:" + MonsterId + ","
        + "AttackId:" + AttackId + ","
        + "Weight:" + Weight + ","
        + "}";
    }
}
}

