
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Monster
{
public sealed partial class MonsterConfig : Luban.BeanBase
{
    public MonsterConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LegacyId = _buf.ReadInt();
        NameCn = _buf.ReadString();
        Desc = _buf.ReadString();
        EntityId = (Entity.EntityId)_buf.ReadInt();
        Level = _buf.ReadInt();
        Hp = _buf.ReadInt();
        Def = _buf.ReadInt();
        Mdef = _buf.ReadInt();
        Crit = _buf.ReadInt();
        Miss = _buf.ReadInt();
        Lucky = _buf.ReadInt();
        Toughness = _buf.ReadInt();
        Htarget = _buf.ReadInt();
        CritReduce = _buf.ReadInt();
        Ar = _buf.ReadInt();
        Sp = _buf.ReadInt();
        RHp = _buf.ReadFloat();
        MoveSpeed = _buf.ReadFloat();
        SightRange = _buf.ReadInt();
        AttackRange = _buf.ReadInt();
        AttackDesire = _buf.ReadInt();
        BehitCalmTime = _buf.ReadFloat();
        AddExp = _buf.ReadInt();
        HurtSoundId = (Sound.SoundId)_buf.ReadInt();
        DeathSoundId = (Sound.SoundId)_buf.ReadInt();
        Gravity = _buf.ReadFloat();
    }

    public static MonsterConfig DeserializeMonsterConfig(ByteBuf _buf)
    {
        return new Monster.MonsterConfig(_buf);
    }

    /// <summary>
    /// 怪物ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 旧怪物编号
    /// </summary>
    public readonly int LegacyId;
    /// <summary>
    /// 中文名
    /// </summary>
    public readonly string NameCn;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 实体枚举
    /// </summary>
    public readonly Entity.EntityId EntityId;
    /// <summary>
    /// 等级(参与等级压制)
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 生命(旧 SHp)
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 物防
    /// </summary>
    public readonly int Def;
    /// <summary>
    /// 魔防
    /// </summary>
    public readonly int Mdef;
    /// <summary>
    /// 暴击
    /// </summary>
    public readonly int Crit;
    /// <summary>
    /// 闪避
    /// </summary>
    public readonly int Miss;
    /// <summary>
    /// 幸运
    /// </summary>
    public readonly int Lucky;
    /// <summary>
    /// 韧性(减对方幸运)
    /// </summary>
    public readonly int Toughness;
    /// <summary>
    /// 命中(破闪)
    /// </summary>
    public readonly int Htarget;
    /// <summary>
    /// 暴击抵抗
    /// </summary>
    public readonly int CritReduce;
    /// <summary>
    /// 破甲(减对方物防)
    /// </summary>
    public readonly int Ar;
    /// <summary>
    /// 破魔(减对方魔防)
    /// </summary>
    public readonly int Sp;
    /// <summary>
    /// 每秒回血(旧 self_rhp)
    /// </summary>
    public readonly float RHp;
    /// <summary>
    /// 移动速度 px/s(旧 speed=8,代码里&#215;10)
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 索敌距离(旧 mysee)
    /// </summary>
    public readonly int SightRange;
    /// <summary>
    /// 进入攻击的距离(旧 attackRange)
    /// </summary>
    public readonly int AttackRange;
    /// <summary>
    /// 攻击欲望 0-100(旧 attackDesire)
    /// </summary>
    public readonly int AttackDesire;
    /// <summary>
    /// 受击后僵直秒数(旧 behit_calmtime)
    /// </summary>
    public readonly float BehitCalmTime;
    /// <summary>
    /// 击杀给英雄的经验(旧 add_exp)
    /// </summary>
    public readonly int AddExp;
    /// <summary>
    /// 受击语音(旧项目怪物无语音素材,填 None;M5 用)
    /// </summary>
    public readonly Sound.SoundId HurtSoundId;
    /// <summary>
    /// 死亡语音(同上)
    /// </summary>
    public readonly Sound.SoundId DeathSoundId;
    /// <summary>
    /// 重力 px/s&#178;(旧 gravity=980 向下)
    /// </summary>
    public readonly float Gravity;
   
    public const int __ID__ = 129443944;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "LegacyId:" + LegacyId + ","
        + "NameCn:" + NameCn + ","
        + "Desc:" + Desc + ","
        + "EntityId:" + EntityId + ","
        + "Level:" + Level + ","
        + "Hp:" + Hp + ","
        + "Def:" + Def + ","
        + "Mdef:" + Mdef + ","
        + "Crit:" + Crit + ","
        + "Miss:" + Miss + ","
        + "Lucky:" + Lucky + ","
        + "Toughness:" + Toughness + ","
        + "Htarget:" + Htarget + ","
        + "CritReduce:" + CritReduce + ","
        + "Ar:" + Ar + ","
        + "Sp:" + Sp + ","
        + "RHp:" + RHp + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "SightRange:" + SightRange + ","
        + "AttackRange:" + AttackRange + ","
        + "AttackDesire:" + AttackDesire + ","
        + "BehitCalmTime:" + BehitCalmTime + ","
        + "AddExp:" + AddExp + ","
        + "HurtSoundId:" + HurtSoundId + ","
        + "DeathSoundId:" + DeathSoundId + ","
        + "Gravity:" + Gravity + ","
        + "}";
    }
}
}

