
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Monster
{ 
    public enum MonsterRank
    {
        /// <summary>
        /// 普通
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 精英
        /// </summary>
        Elite = 1,
        /// <summary>
        /// 首领
        /// </summary>
        Boss = 2,
    }

} 

