
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Monster
{
public partial class TbMonsterAttackConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Monster.MonsterAttackConfig> _dataMap;
    private readonly System.Collections.Generic.List<Monster.MonsterAttackConfig> _dataList;
    
    public TbMonsterAttackConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Monster.MonsterAttackConfig>(n);
        _dataList = new System.Collections.Generic.List<Monster.MonsterAttackConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Monster.MonsterAttackConfig _v;
            _v = global::GameConfig.Monster.MonsterAttackConfig.DeserializeMonsterAttackConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Monster.MonsterAttackConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Monster.MonsterAttackConfig> DataList => _dataList;

    public Monster.MonsterAttackConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Monster.MonsterAttackConfig Get(int key) => _dataMap[key];
    public Monster.MonsterAttackConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

