//------------------------------------------------------------
// Resources Collection Constant
// Auto-generated by GameFrameworkTopMenu plugin.
// Do not modify manually.
// Generation time: 2026-10-07 16:05:28
//------------------------------------------------------------

namespace GameConfig.Constant
{
	public static class ResourcesCollectionConstant
{
		public const string Audios_AudioBundle = "res://TheGame/Audios/AudioBundle.tres";
		public const string Audios_AudioBus = "res://TheGame/Audios/AudioBus.tres";
		public const string wukong_wukong_attack_1_3 = "res://TheGame/Audios/SFX/wukong/wukong_attack_1_3.mp3";
		public const string wukong_wukong_attack_2 = "res://TheGame/Audios/SFX/wukong/wukong_attack_2.mp3";
		public const string wukong_wukong_attack_4 = "res://TheGame/Audios/SFX/wukong/wukong_attack_4.mp3";
		public const string wukong_wukong_death = "res://TheGame/Audios/SFX/wukong/wukong_death.mp3";
		public const string wukong_wukong_hit_impact = "res://TheGame/Audios/SFX/wukong/wukong_hit_impact.mp3";
		public const string wukong_wukong_hurt = "res://TheGame/Audios/SFX/wukong/wukong_hurt.mp3";
		public const string DataTables_DataTableBundle = "res://TheGame/DataTables/DataTableBundle.tres";
		public const string GameConfigs_battle_tbattackconfig = "res://TheGame/DataTables/GameConfigs/battle_tbattackconfig.bytes";
		public const string GameConfigs_battle_tbbattleconfig = "res://TheGame/DataTables/GameConfigs/battle_tbbattleconfig.bytes";
		public const string GameConfigs_entity_tbentityconfig = "res://TheGame/DataTables/GameConfigs/entity_tbentityconfig.bytes";
		public const string GameConfigs_hero_tbheroconfig = "res://TheGame/DataTables/GameConfigs/hero_tbheroconfig.bytes";
		public const string GameConfigs_hero_tbherolevelconfig = "res://TheGame/DataTables/GameConfigs/hero_tbherolevelconfig.bytes";
		public const string GameConfigs_level_tblevelconfig = "res://TheGame/DataTables/GameConfigs/level_tblevelconfig.bytes";
		public const string GameConfigs_monster_tbmonsterconfig = "res://TheGame/DataTables/GameConfigs/monster_tbmonsterconfig.bytes";
		public const string GameConfigs_sound_tbsoundconfig = "res://TheGame/DataTables/GameConfigs/sound_tbsoundconfig.bytes";
		public const string GameConfigs_ui_tbuiformconfig = "res://TheGame/DataTables/GameConfigs/ui_tbuiformconfig.bytes";
		public const string Localizations_ChineseSimplified = "res://TheGame/DataTables/Localizations/ChineseSimplified.txt";
		public const string Localizations_English = "res://TheGame/DataTables/Localizations/English.txt";
		public const string Animations_demon_monkey_anim_library = "res://TheGame/Entitys/Animations/demon_monkey_anim_library.tres";
		public const string Animations_huaguoshan_monkey_anim_library = "res://TheGame/Entitys/Animations/huaguoshan_monkey_anim_library.tres";
		public const string Animations_wukong_anim_library = "res://TheGame/Entitys/Animations/wukong_anim_library.tres";
		public const string Entitys_DemonMonkeyEntity = "res://TheGame/Entitys/DemonMonkeyEntity.tscn";
		public const string Entitys_EntityBundle = "res://TheGame/Entitys/EntityBundle.tres";
		public const string Entitys_HuaguoshanMonkeyEntity = "res://TheGame/Entitys/HuaguoshanMonkeyEntity.tscn";
		public const string Entitys_WukongEntity = "res://TheGame/Entitys/WukongEntity.tscn";
		public const string Fonts_simhei = "res://TheGame/MainPack/Fonts/simhei.ttf";
		public const string Resources_ArchiveSetting = "res://TheGame/MainPack/Resources/ArchiveSetting.tres";
		public const string Resources_EntityGroupRes = "res://TheGame/MainPack/Resources/EntityGroupRes.tres";
		public const string Resources_NodePoolConfigRes = "res://TheGame/MainPack/Resources/NodePoolConfigRes.tres";
		public const string Resources_ScriptGenerateRes = "res://TheGame/MainPack/Resources/ScriptGenerateRes.tres";
		public const string Resources_SoundGroupRes = "res://TheGame/MainPack/Resources/SoundGroupRes.tres";
		public const string Resources_UIGroupRes = "res://TheGame/MainPack/Resources/UIGroupRes.tres";
		public const string Resources_UpdateSettingRes = "res://TheGame/MainPack/Resources/UpdateSettingRes.tres";
		public const string Themes_MainThemes = "res://TheGame/MainPack/Themes/MainThemes.tres";
		public const string UI_LoadingForm = "res://TheGame/MainPack/UI/LoadingForm.tscn";
		public const string UI_QuestionTips = "res://TheGame/MainPack/UI/QuestionTips.tscn";
		public const string Scenes_DebugArena = "res://TheGame/Scenes/DebugArena.tscn";
		public const string Scenes_Level_1 = "res://TheGame/Scenes/Level_1.tscn";
		public const string Scenes_ScenesBundle = "res://TheGame/Scenes/ScenesBundle.tres";
		public const string Scenes_TestArena = "res://TheGame/Scenes/TestArena.tscn";
		public const string Sprites_bhpic = "res://TheGame/Sprites/bhpic.png";
		public const string Sprites_bhyhIcon = "res://TheGame/Sprites/bhyhIcon.png";
		public const string wukong_wukong_body = "res://TheGame/Sprites/Characters/Heroes/wukong/wukong_body.png";
		public const string wukong_wukong_weapon_dragon_blade = "res://TheGame/Sprites/Characters/Heroes/wukong/wukong_weapon_dragon_blade.png";
		public const string wukong_wukong_weapon_empty = "res://TheGame/Sprites/Characters/Heroes/wukong/wukong_weapon_empty.png";
		public const string wukong_wukong_weapon_golden_cudgel = "res://TheGame/Sprites/Characters/Heroes/wukong/wukong_weapon_golden_cudgel.png";
		public const string wukong_wukong_weapon_purple_gold_cudgel = "res://TheGame/Sprites/Characters/Heroes/wukong/wukong_weapon_purple_gold_cudgel.png";
		public const string wukong_wukong_weapon_wooden_stick = "res://TheGame/Sprites/Characters/Heroes/wukong/wukong_weapon_wooden_stick.png";
		public const string demon_monkey_demon_monkey_animations = "res://TheGame/Sprites/Characters/Monsters/demon_monkey/demon_monkey_animations.tres";
		public const string demon_monkey_demon_monkey_attack = "res://TheGame/Sprites/Characters/Monsters/demon_monkey/demon_monkey_attack.png";
		public const string demon_monkey_demon_monkey_death = "res://TheGame/Sprites/Characters/Monsters/demon_monkey/demon_monkey_death.png";
		public const string demon_monkey_demon_monkey_hurt = "res://TheGame/Sprites/Characters/Monsters/demon_monkey/demon_monkey_hurt.png";
		public const string demon_monkey_demon_monkey_idle = "res://TheGame/Sprites/Characters/Monsters/demon_monkey/demon_monkey_idle.png";
		public const string demon_monkey_demon_monkey_run = "res://TheGame/Sprites/Characters/Monsters/demon_monkey/demon_monkey_run.png";
		public const string huaguoshan_monkey_huaguoshan_monkey_animations = "res://TheGame/Sprites/Characters/Monsters/huaguoshan_monkey/huaguoshan_monkey_animations.tres";
		public const string huaguoshan_monkey_huaguoshan_monkey_attack = "res://TheGame/Sprites/Characters/Monsters/huaguoshan_monkey/huaguoshan_monkey_attack.png";
		public const string huaguoshan_monkey_huaguoshan_monkey_death = "res://TheGame/Sprites/Characters/Monsters/huaguoshan_monkey/huaguoshan_monkey_death.png";
		public const string huaguoshan_monkey_huaguoshan_monkey_hurt = "res://TheGame/Sprites/Characters/Monsters/huaguoshan_monkey/huaguoshan_monkey_hurt.png";
		public const string huaguoshan_monkey_huaguoshan_monkey_idle = "res://TheGame/Sprites/Characters/Monsters/huaguoshan_monkey/huaguoshan_monkey_idle.png";
		public const string huaguoshan_monkey_huaguoshan_monkey_run = "res://TheGame/Sprites/Characters/Monsters/huaguoshan_monkey/huaguoshan_monkey_run.png";
		public const string wukong_wukong_effect_animations = "res://TheGame/Sprites/Effects/wukong/wukong_effect_animations.tres";
		public const string wukong_wukong_hit_1 = "res://TheGame/Sprites/Effects/wukong/wukong_hit_1.png";
		public const string wukong_wukong_hit_2 = "res://TheGame/Sprites/Effects/wukong/wukong_hit_2.png";
		public const string wukong_wukong_hit_3 = "res://TheGame/Sprites/Effects/wukong/wukong_hit_3.png";
		public const string wukong_wukong_hit_4 = "res://TheGame/Sprites/Effects/wukong/wukong_hit_4.png";
		public const string huaguoshan_level_1_bg_end = "res://TheGame/Sprites/Levels/huaguoshan/level_1_bg_end.png";
		public const string huaguoshan_level_1_floor = "res://TheGame/Sprites/Levels/huaguoshan/level_1_floor.png";
		public const string huaguoshan_level_1_front = "res://TheGame/Sprites/Levels/huaguoshan/level_1_front.png";
		public const string Number_damage_number_hero_magic = "res://TheGame/Sprites/Number/damage_number_hero_magic.png";
		public const string Number_damage_number_hero_physics = "res://TheGame/Sprites/Number/damage_number_hero_physics.png";
		public const string Number_damage_number_miss = "res://TheGame/Sprites/Number/damage_number_miss.png";
		public const string Number_damage_number_monster_magic_crit = "res://TheGame/Sprites/Number/damage_number_monster_magic_crit.png";
		public const string Number_damage_number_monster_magic = "res://TheGame/Sprites/Number/damage_number_monster_magic.png";
		public const string Number_damage_number_monster_physics_crit = "res://TheGame/Sprites/Number/damage_number_monster_physics_crit.png";
		public const string Number_damage_number_monster_physics = "res://TheGame/Sprites/Number/damage_number_monster_physics.png";
		public const string Number_damage_number_real = "res://TheGame/Sprites/Number/damage_number_real.png";
		public const string Sprites_SpritesBundle = "res://TheGame/Sprites/SpritesBundle.tres";
		public const string gogo_gogo_animations = "res://TheGame/Sprites/UI/gogo/gogo_animations.tres";
		public const string gogo_gogo_sheet = "res://TheGame/Sprites/UI/gogo/gogo_sheet.png";
		public const string hud_hud_exp_fill = "res://TheGame/Sprites/UI/hud/hud_exp_fill.png";
		public const string hud_hud_head_wukong = "res://TheGame/Sprites/UI/hud/hud_head_wukong.png";
		public const string hud_hud_hp_delay = "res://TheGame/Sprites/UI/hud/hud_hp_delay.png";
		public const string hud_hud_hp_fill = "res://TheGame/Sprites/UI/hud/hud_hp_fill.png";
		public const string hud_hud_menu_panel = "res://TheGame/Sprites/UI/hud/hud_menu_panel.png";
		public const string hud_hud_mp_fill = "res://TheGame/Sprites/UI/hud/hud_mp_fill.png";
		public const string hud_hud_status_label = "res://TheGame/Sprites/UI/hud/hud_status_label.png";
		public const string hud_hud_status_panel = "res://TheGame/Sprites/UI/hud/hud_status_panel.png";
		public const string hud_hud_ws_fill = "res://TheGame/Sprites/UI/hud/hud_ws_fill.png";
		public const string hud_hud_ws_frame = "res://TheGame/Sprites/UI/hud/hud_ws_frame.png";
		public const string hud_hud_ws_grey = "res://TheGame/Sprites/UI/hud/hud_ws_grey.png";
		public const string hud_hud_ws_max_sheet = "res://TheGame/Sprites/UI/hud/hud_ws_max_sheet.png";
		public const string hud_hud_ws_under = "res://TheGame/Sprites/UI/hud/hud_ws_under.png";
		public const string UIs_BattleHud = "res://TheGame/UIs/BattleHud.tscn";
		public const string UIs_DamagePop = "res://TheGame/UIs/DamagePop.tscn";
		public const string UIs_UIsBundle = "res://TheGame/UIs/UIsBundle.tres";
	}
}
