
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum UIFormId
    {
        /// <summary>
        /// 选人界面
        /// </summary>
        HeroSelectForm = 0,
        /// <summary>
        /// 战斗界面
        /// </summary>
        HudForm = 1,
        /// <summary>
        /// 结算界面
        /// </summary>
        GameOverForm = 2,
    }

} 

